package Almacen;

// Generated 17-feb-2015 17:27:05 by Hibernate Tools 3.4.0.CR1

/**
 * DescargasProductos generated by hbm2java
 */
public class DescargasProductos implements java.io.Serializable {

	private DescargasProductosId id;
	private int cantidadTotal;
	private int cantidadDescargada;

	public DescargasProductos() {
	}

	public DescargasProductos(DescargasProductosId id, int cantidadTotal,
			int cantidadDescargada) {
		this.id = id;
		this.cantidadTotal = cantidadTotal;
		this.cantidadDescargada = cantidadDescargada;
	}

	public DescargasProductosId getId() {
		return this.id;
	}

	public void setId(DescargasProductosId id) {
		this.id = id;
	}

	public int getCantidadTotal() {
		return this.cantidadTotal;
	}

	public void setCantidadTotal(int cantidadTotal) {
		this.cantidadTotal = cantidadTotal;
	}

	public int getCantidadDescargada() {
		return this.cantidadDescargada;
	}

	public void setCantidadDescargada(int cantidadDescargada) {
		this.cantidadDescargada = cantidadDescargada;
	}

}
