package Almacen;

// Generated 17-feb-2015 17:27:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	private Integer idPedido;
	private String nombre;
	private String apellidos;
	private String telefono;
	private String direccion;
	private double precio;
	private Date fecha;
	private int idCarga;

	public Pedido() {
	}

	public Pedido(String nombre, String apellidos, String telefono,
			String direccion, double precio, Date fecha, int idCarga) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.telefono = telefono;
		this.direccion = direccion;
		this.precio = precio;
		this.fecha = fecha;
		this.idCarga = idCarga;
	}

	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public int getIdCarga() {
		return this.idCarga;
	}

	public void setIdCarga(int idCarga) {
		this.idCarga = idCarga;
	}

}
