package Almacen;

// Generated 17-feb-2015 17:27:05 by Hibernate Tools 3.4.0.CR1

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private int ean;
	private int asi;
	private String fabricante;
	private String modelo;
	private String descripcion;
	private double precio;
	private double alto;
	private double ancho;
	private double largo;
	private double peso;

	public Productos() {
	}

	public Productos(int ean, int asi, String fabricante, String modelo,
			String descripcion, double precio, double alto, double ancho,
			double largo, double peso) {
		this.ean = ean;
		this.asi = asi;
		this.fabricante = fabricante;
		this.modelo = modelo;
		this.descripcion = descripcion;
		this.precio = precio;
		this.alto = alto;
		this.ancho = ancho;
		this.largo = largo;
		this.peso = peso;
	}

	public int getEan() {
		return this.ean;
	}

	public void setEan(int ean) {
		this.ean = ean;
	}

	public int getAsi() {
		return this.asi;
	}

	public void setAsi(int asi) {
		this.asi = asi;
	}

	public String getFabricante() {
		return this.fabricante;
	}

	public void setFabricante(String fabricante) {
		this.fabricante = fabricante;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public double getAlto() {
		return this.alto;
	}

	public void setAlto(double alto) {
		this.alto = alto;
	}

	public double getAncho() {
		return this.ancho;
	}

	public void setAncho(double ancho) {
		this.ancho = ancho;
	}

	public double getLargo() {
		return this.largo;
	}

	public void setLargo(double largo) {
		this.largo = largo;
	}

	public double getPeso() {
		return this.peso;
	}

	public void setPeso(double peso) {
		this.peso = peso;
	}

}
