package Almacen;

// Generated 24-feb-2015 16:55:43 by Hibernate Tools 3.4.0.CR1

/**
 * ProductosPedidos generated by hbm2java
 */
public class ProductosPedidos implements java.io.Serializable {

	private ProductosPedidosId id;

	public ProductosPedidos() {
	}

	public ProductosPedidos(ProductosPedidosId id) {
		this.id = id;
	}

	public ProductosPedidosId getId() {
		return this.id;
	}

	public void setId(ProductosPedidosId id) {
		this.id = id;
	}

}
