package Almacen;

// Generated 17-feb-2015 17:27:05 by Hibernate Tools 3.4.0.CR1

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores implements java.io.Serializable {

	private Integer idProveedor;
	private String cif;
	private String nombre;
	private String descripcion;
	private String direccion;
	private String telefono;

	public Proveedores() {
	}

	public Proveedores(String cif, String nombre, String descripcion,
			String direccion, String telefono) {
		this.cif = cif;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.telefono = telefono;
	}

	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
