package Almacen;

// Generated 17-feb-2015 17:27:05 by Hibernate Tools 3.4.0.CR1

/**
 * UbicacionProductos generated by hbm2java
 */
public class UbicacionProductos implements java.io.Serializable {

	private UbicacionProductosId id;

	public UbicacionProductos() {
	}

	public UbicacionProductos(UbicacionProductosId id) {
		this.id = id;
	}

	public UbicacionProductosId getId() {
		return this.id;
	}

	public void setId(UbicacionProductosId id) {
		this.id = id;
	}

}
