package Almacen;

// Generated 24-feb-2015 16:55:43 by Hibernate Tools 3.4.0.CR1

/**
 * UbicacionProductos generated by hbm2java
 */
public class UbicacionProductos implements java.io.Serializable {

	private UbicacionProductosId id;
	private int cantidad;

	public UbicacionProductos() {
	}

	public UbicacionProductos(UbicacionProductosId id, int cantidad) {
		this.id = id;
		this.cantidad = cantidad;
	}

	public UbicacionProductosId getId() {
		return this.id;
	}

	public void setId(UbicacionProductosId id) {
		this.id = id;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
